# Generated by Django 5.1.4 on 2025-12-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=400.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='equipment',
            name='rental_price',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=8),
        ),
    ]
